import { supabase } from '../lib/supabase';
export type Attendance={id:string;public_id:string;client_id:string|null;status:string;started_at:string|null;completed_at:string|null;notes:string|null};
export type AttendanceOrder={id:string;attendance_id:string|null;public_id:string;status:string;total_amount:number};
export type StartableAppointment={id:string;client_id:string|null;starts_at:string;status:string};
export async function listAttendances(companyId:string,unitId:string,start:string,end:string){const {data,error}=await supabase.from('attendances').select('id,public_id,client_id,status,started_at,completed_at,notes').eq('company_id',companyId).eq('unit_id',unitId).gte('started_at',start).lt('started_at',end).order('started_at',{ascending:false});if(error)throw error;return(data??[]) as Attendance[]}
export async function listOrders(attendanceIds:string[]){if(!attendanceIds.length)return[];const {data,error}=await supabase.from('orders').select('id,attendance_id,public_id,status,total_amount').in('attendance_id',attendanceIds);if(error)throw error;return(data??[]).map((x:any)=>({...x,total_amount:Number(x.total_amount||0)})) as AttendanceOrder[]}
export async function listStartableAppointments(companyId:string,unitId:string,start:string,end:string){const {data,error}=await supabase.from('appointments').select('id,client_id,starts_at,status').eq('company_id',companyId).eq('unit_id',unitId).gte('starts_at',start).lt('starts_at',end).in('status',['scheduled','confirmed']).order('starts_at');if(error)throw error;return(data??[]) as StartableAppointment[]}
export async function startAttendance(appointmentId:string){const {data,error}=await supabase.rpc('start_attendance_from_appointment',{p_appointment_id:appointmentId});if(error)throw error;return data as string}
export async function completeAttendance(attendanceId:string){const {data,error}=await supabase.rpc('complete_attendance_and_open_order',{p_attendance_id:attendanceId});if(error)throw error;return data as string}
