import { useEffect,useMemo,useState } from 'react';
import { CheckCircle2,PlayCircle,ReceiptText } from 'lucide-react';
import { useAuthTenant } from '../auth/AuthTenantProvider';
import { formatUnitTime,nextDateText,unitDateText,zonedDateTimeToIso } from '../lib/timezone';
import { listAgendaClients,type AgendaClient } from '../agenda/agendaService';
import { completeAttendance,listAttendances,listOrders,listStartableAppointments,startAttendance,type Attendance,type AttendanceOrder,type StartableAppointment } from './attendanceService';

export function AttendancePage(){const {company,unit}=useAuthTenant();const zone=unit?.timezone||'America/Sao_Paulo';const [appointments,setAppointments]=useState<StartableAppointment[]>([]);const [attendances,setAttendances]=useState<Attendance[]>([]);const [orders,setOrders]=useState<AttendanceOrder[]>([]);const [clients,setClients]=useState<AgendaClient[]>([]);const [status,setStatus]=useState<'loading'|'ready'|'error'>('loading');const [busy,setBusy]=useState<string|null>(null);const [actionError,setActionError]=useState<string|null>(null);
 async function load(){if(!company||!unit)return;setStatus('loading');try{const date=unitDateText(zone),start=zonedDateTimeToIso(date,'00:00',zone),end=zonedDateTimeToIso(nextDateText(date),'00:00',zone);const [a,t,c]=await Promise.all([listStartableAppointments(company.id,unit.id,start,end),listAttendances(company.id,unit.id,start,end),listAgendaClients(company.id)]);setAppointments(a);setAttendances(t);setClients(c);setOrders(await listOrders(t.map(x=>x.id)));setStatus('ready')}catch{setStatus('error')}}
 useEffect(()=>{void load()},[company?.id,unit?.id,zone]);
 const names=useMemo(()=>new Map(clients.map(x=>[x.id,x.full_name])),[clients]);const orderByAttendance=useMemo(()=>new Map(orders.map(x=>[x.attendance_id,x])),[orders]);
 async function start(id:string){setBusy(id);setActionError(null);try{await startAttendance(id);await load()}catch(e){setActionError(e instanceof Error?e.message:'Não foi possível iniciar o atendimento.')}finally{setBusy(null)}}
 async function complete(id:string){setBusy(id);setActionError(null);try{await completeAttendance(id);await load()}catch(e){setActionError(e instanceof Error?e.message:'Não foi possível concluir o atendimento.')}finally{setBusy(null)}}
 return <section className="content attendance-page"><div className="page-head"><div><p className="eyebrow">ATENDIMENTO</p><h1>Da agenda à comanda, sem atalhos.</h1><p className="lead">Início e conclusão usam os RPCs protegidos do Salúnea. A conclusão abre a comanda pelo backend e mantém a cadeia operacional íntegra.</p></div></div>{actionError&&<div className="form-error attendance-error">{actionError}</div>}{status==='loading'&&<div className="state-card">Carregando operação do dia…</div>}{status==='error'&&<div className="state-card error">Não foi possível carregar o atendimento. Nenhum dado foi alterado.<button onClick={()=>void load()}>Tentar novamente</button></div>}{status==='ready'&&<div className="attendance-grid"><section className="operation-card"><h2>Agendados para hoje</h2>{appointments.length===0?<p className="empty-copy">Nenhum agendamento aguardando início.</p>:appointments.map(a=><article className="operation-row" key={a.id}><div><strong>{a.client_id?names.get(a.client_id)||'Cliente':'Cliente'}</strong><span>{formatUnitTime(a.starts_at,zone)} · {a.status}</span></div><button className="primary" disabled={busy===a.id} onClick={()=>void start(a.id)}><PlayCircle size={16}/>{busy===a.id?'Iniciando…':'Iniciar'}</button></article>)}</section><section className="operation-card"><h2>Fluxo do dia</h2>{attendances.length===0?<p className="empty-copy">Nenhum atendimento iniciado hoje.</p>:attendances.map(a=>{const order=orderByAttendance.get(a.id);return <article className="operation-row" key={a.id}><div><strong>{a.client_id?names.get(a.client_id)||'Cliente':'Cliente'}</strong><span>{a.public_id} · {a.status==='in_progress'?'Em atendimento':a.status==='completed'?'Concluído':a.status}</span>{order&&<small><ReceiptText size={13}/>{order.public_id} · {order.status} · R$ {order.total_amount.toFixed(2)}</small>}</div>{a.status==='in_progress'?<button className="primary" disabled={busy===a.id} onClick={()=>void complete(a.id)}><CheckCircle2 size={16}/>{busy===a.id?'Concluindo…':'Concluir'}</button>:<span className="done-badge"><CheckCircle2 size={14}/>Concluído</span>}</article>})}</section></div>}</section>}
