import { supabase } from '../lib/supabase';
export type CashOrder={id:string;public_id:string;client_id:string|null;status:string;total_amount:number;created_at:string};
export type Payment={id:string;order_id:string|null;public_id:string;payment_method:string;amount:number;status:string;occurred_at:string};
export type Refund={id:string;payment_record_id:string;order_id:string;amount:number;reason:string;refunded_at:string};
export const paymentMethods=['cash','pix','debit_card','credit_card','bank_transfer','deposit_credit','package_credit','other'] as const;
export async function listCashOrders(companyId:string,unitId:string,start:string,end:string){const {data,error}=await supabase.from('orders').select('id,public_id,client_id,status,total_amount,created_at').eq('company_id',companyId).eq('unit_id',unitId).gte('created_at',start).lt('created_at',end).order('created_at',{ascending:false});if(error)throw error;return(data??[]).map((x:any)=>({...x,total_amount:Number(x.total_amount||0)})) as CashOrder[]}
export async function listPayments(companyId:string,unitId:string,start:string,end:string){const {data,error}=await supabase.from('payment_records').select('id,order_id,public_id,payment_method,amount,status,occurred_at').eq('company_id',companyId).eq('unit_id',unitId).gte('occurred_at',start).lt('occurred_at',end).order('occurred_at',{ascending:false});if(error)throw error;return(data??[]).map((x:any)=>({...x,amount:Number(x.amount||0)})) as Payment[]}
export async function listRefunds(companyId:string,unitId:string,start:string,end:string){const {data,error}=await supabase.from('payment_refunds').select('id,payment_record_id,order_id,amount,reason,refunded_at').eq('company_id',companyId).eq('unit_id',unitId).gte('refunded_at',start).lt('refunded_at',end).order('refunded_at',{ascending:false});if(error)throw error;return(data??[]).map((x:any)=>({...x,amount:Number(x.amount||0)})) as Refund[]}
export async function receivePayment(orderId:string,method:string,amount:number,idempotencyKey:string){const {data,error}=await supabase.rpc('receive_order_payment',{p_order_id:orderId,p_payment_method:method,p_amount:amount,p_idempotency_key:idempotencyKey});if(error)throw error;return data as string}
export async function refundPayment(paymentId:string,amount:number,reason:string,idempotencyKey:string){const {data,error}=await supabase.rpc('refund_order_payment',{p_payment_record_id:paymentId,p_amount:amount,p_reason:reason.trim(),p_idempotency_key:idempotencyKey});if(error)throw error;return data as string}
export async function closeOrder(orderId:string){const {data,error}=await supabase.rpc('close_order',{p_order_id:orderId});if(error)throw error;return data}
export function netForPayment(payment:Payment,refunds:Refund[]){if(payment.status==='cancelled')return 0;return Math.max(0,payment.amount-refunds.filter(r=>r.payment_record_id===payment.id).reduce((s,r)=>s+r.amount,0))}
