import { useEffect,useState,type FormEvent } from 'react';
import { Boxes,PackagePlus } from 'lucide-react';
import { useAuthTenant } from '../auth/AuthTenantProvider';
import { listProjectedStock,recordStockMovement,type StockMovementType,type StockRow } from './stockService';
const num=(n:number)=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format(n);
const units:Record<string,string>={unit:'unidade',piece:'peça',liter:'litro',kilogram:'quilo',milliliter:'mililitro',gram:'grama'};
export function StockPage(){const {company,unit}=useAuthTenant();const [rows,setRows]=useState<StockRow[]>([]);const [status,setStatus]=useState<'loading'|'ready'|'error'>('loading');const [selected,setSelected]=useState('');const [type,setType]=useState<StockMovementType>('purchase');const [quantity,setQuantity]=useState('');const [cost,setCost]=useState('');const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [feedback,setFeedback]=useState<string|null>(null);
 async function load(){if(!company||!unit)return;setStatus('loading');try{const data=await listProjectedStock(company.id,unit.id);setRows(data);setSelected(s=>data.some(x=>x.unit_product_id===s)?s:(data[0]?.unit_product_id||''));setStatus('ready')}catch{setStatus('error')}}useEffect(()=>{void load()},[company?.id,unit?.id]);
 async function submit(e:FormEvent){e.preventDefault();if(!company||!unit||!selected)return;const qty=Number(quantity.replace(',','.')),unitCost=cost.trim()===''?null:Number(cost.replace(',','.'));if(!(qty>0)){setFeedback('Informe uma quantidade positiva.');return}if(type==='purchase'&&(unitCost===null||!Number.isFinite(unitCost)||unitCost<0)){setFeedback('Compra exige custo unitário válido.');return}setBusy(true);setFeedback(null);try{await recordStockMovement({companyId:company.id,unitId:unit.id,unitProductId:selected,movementType:type,quantity:qty,unitCost,reason:reason.trim()||null});setQuantity('');setCost('');setReason('');setFeedback('Movimentação registrada e saldo confirmado.');await load()}catch{setFeedback('Não foi possível confirmar a movimentação. Atualize o estoque antes de tentar novamente.')}finally{setBusy(false)}}
 return <section className="content stock-page"><div className="page-head"><div><p className="eyebrow">ESTOQUE</p><h1>Saldo real e projeção no mesmo lugar.</h1><p className="lead">O Salúnea usa o estoque projetado validado no backend e registra entradas e saídas por movimentação idempotente.</p></div></div>{status==='loading'&&<div className="state-card">Carregando estoque da unidade…</div>}{status==='error'&&<div className="state-card error">Não foi possível carregar o estoque. Nada foi alterado.<button onClick={()=>void load()}>Tentar novamente</button></div>}{status==='ready'&&<><div className="stock-grid">{rows.length===0?<div className="state-card">Nenhum produto de estoque configurado nesta unidade.</div>:rows.map(x=>{const low=x.on_hand<x.minimum_stock;return <article key={x.unit_product_id} className="operation-card"><div className="stock-title"><Boxes size={18}/><strong>{x.product_name}</strong></div><span>{units[String(x.unit_of_measure||'').toLowerCase()]||x.unit_of_measure||'unidade'}</span><div className="cash-summary"><div><span>Saldo</span><strong>{num(x.on_hand)}</strong></div><div><span>Mínimo</span><strong>{num(x.minimum_stock)}</strong></div><div><span>Projetado</span><strong>{num(x.projected_quantity)}</strong></div></div><small>Entrada confiável {num(x.reliable_expected_inbound)} · comprometido futuro {num(x.future_committed)}</small>{low&&<div className="done-badge">Abaixo do mínimo</div>}</article>})}</div>{rows.length>0&&<form className="operation-card payment-form" onSubmit={submit}><h2><PackagePlus size={20}/>Movimentação controlada</h2><label>Produto<select value={selected} onChange={e=>setSelected(e.target.value)}>{rows.map(x=><option key={x.unit_product_id} value={x.unit_product_id}>{x.product_name}</option>)}</select></label><label>Tipo<select value={type} onChange={e=>setType(e.target.value as StockMovementType)}><option value="purchase">Entrada / compra</option><option value="adjustment_in">Ajuste de entrada</option><option value="sale">Saída / venda</option><option value="loss">Perda</option><option value="service_consumption">Consumo de serviço</option></select></label><label>Quantidade<input inputMode="decimal" value={quantity} onChange={e=>setQuantity(e.target.value)} required/></label><label>Custo unitário<input inputMode="decimal" value={cost} onChange={e=>setCost(e.target.value)} placeholder={type==='purchase'?'Obrigatório para compra':'Opcional'}/></label><label>Motivo<input maxLength={180} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="primary" disabled={busy}>{busy?'Registrando…':'Registrar movimentação'}</button>{feedback&&<div className="form-error attendance-error">{feedback}</div>}</form>}</>}</section>}
