import { useEffect,useMemo,useState } from 'react';
import { Search,UserPlus } from 'lucide-react';
import { useAuthTenant } from '../auth/AuthTenantProvider';
import { hasActiveWhatsappConsent,listActiveClients,type ClientRow } from './clientService';

export function ClientsPage(){const {company}=useAuthTenant();const [rows,setRows]=useState<ClientRow[]>([]);const [status,setStatus]=useState<'loading'|'ready'|'error'>('loading');const [query,setQuery]=useState('');
 async function load(){if(!company)return;setStatus('loading');try{setRows(await listActiveClients(company.id));setStatus('ready');}catch{setStatus('error');}}
 useEffect(()=>{void load();},[company?.id]);
 const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase('pt-BR');if(!q)return rows;return rows.filter(x=>`${x.full_name} ${x.phone??''}`.toLocaleLowerCase('pt-BR').includes(q));},[rows,query]);
 return <section className="content clients-page"><div className="page-head"><div><p className="eyebrow">RELACIONAMENTO</p><h1>Clientes</h1><p className="lead">Cada cadastro pertence à empresa ativa e alimentará histórico, recorrência e recuperação.</p></div><button className="primary" disabled title="Criação será habilitada após validar a assinatura exata do RPC create_client"><UserPlus size={17}/>Novo cliente</button></div><label className="client-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nome ou telefone"/></label>{status==='loading'&&<div className="state-card">Carregando clientes reais…</div>}{status==='error'&&<div className="state-card error">Não foi possível carregar os clientes. Nenhum dado foi alterado.<button onClick={()=>void load()}>Tentar novamente</button></div>}{status==='ready'&&filtered.length===0&&<div className="state-card">Nenhum cliente encontrado nesta empresa.</div>}{status==='ready'&&filtered.length>0&&<div className="client-list">{filtered.map(client=><article className="client-row" key={client.id}><div className="avatar">{client.full_name.trim().charAt(0).toUpperCase()||'C'}</div><div><strong>{client.full_name}</strong><span>{client.phone||'Sem telefone'}</span></div><div className={hasActiveWhatsappConsent(client)?'consent active':'consent'}>{hasActiveWhatsappConsent(client)?'WhatsApp autorizado':'Sem consentimento WhatsApp'}</div></article>)}</div>}</section>}
