import { useEffect,useMemo,useState,type FormEvent } from 'react';
import { Search,UserPlus,X } from 'lucide-react';
import { useAuthTenant } from '../auth/AuthTenantProvider';
import { createClient,hasActiveWhatsappConsent,listActiveClients,type ClientRow } from './clientService';

export function ClientsPage(){const {company}=useAuthTenant();const [rows,setRows]=useState<ClientRow[]>([]);const [status,setStatus]=useState<'loading'|'ready'|'error'>('loading');const [query,setQuery]=useState('');const [open,setOpen]=useState(false);const [name,setName]=useState('');const [phone,setPhone]=useState('');const [saving,setSaving]=useState(false);const [formError,setFormError]=useState<string|null>(null);
 async function load(){if(!company)return;setStatus('loading');try{setRows(await listActiveClients(company.id));setStatus('ready');}catch{setStatus('error');}}
 useEffect(()=>{void load();},[company?.id]);
 const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase('pt-BR');if(!q)return rows;return rows.filter(x=>`${x.full_name} ${x.phone??''}`.toLocaleLowerCase('pt-BR').includes(q));},[rows,query]);
 function close(){if(saving)return;setOpen(false);setName('');setPhone('');setFormError(null)}
 async function submit(e:FormEvent){e.preventDefault();if(!company)return;const clean=name.trim();if(!clean){setFormError('Informe o nome da cliente.');return}setSaving(true);setFormError(null);try{await createClient(company.id,clean,phone);await load();setSaving(false);close()}catch(e){setFormError(e instanceof Error?e.message:'Não foi possível cadastrar a cliente.');setSaving(false)}}
 return <section className="content clients-page"><div className="page-head"><div><p className="eyebrow">RELACIONAMENTO</p><h1>Clientes</h1><p className="lead">Cada cadastro pertence à empresa ativa e alimentará histórico, recorrência e recuperação.</p></div><button className="primary" onClick={()=>setOpen(true)}><UserPlus size={17}/>Novo cliente</button></div><label className="client-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por nome ou telefone"/></label>{status==='loading'&&<div className="state-card">Carregando clientes reais…</div>}{status==='error'&&<div className="state-card error">Não foi possível carregar os clientes. Nenhum dado foi alterado.<button onClick={()=>void load()}>Tentar novamente</button></div>}{status==='ready'&&filtered.length===0&&<div className="state-card">Nenhum cliente encontrado nesta empresa.</div>}{status==='ready'&&filtered.length>0&&<div className="client-list">{filtered.map(client=><article className="client-row" key={client.id}><div className="avatar">{client.full_name.trim().charAt(0).toUpperCase()||'C'}</div><div><strong>{client.full_name}</strong><span>{client.phone||'Sem telefone'}</span></div><div className={hasActiveWhatsappConsent(client)?'consent active':'consent'}>{hasActiveWhatsappConsent(client)?'WhatsApp autorizado':'Sem consentimento WhatsApp'}</div></article>)}</div>}{open&&<div className="dialog-backdrop"><form className="client-dialog" onSubmit={submit}><div className="dialog-head"><div><p className="eyebrow">NOVO CLIENTE</p><h2>Comece pelo essencial.</h2></div><button type="button" className="icon-button" onClick={close} aria-label="Fechar"><X size={20}/></button></div><p>O telefone é validado dentro da empresa. Um número já usado por cliente ativo é bloqueado pelo backend.</p><label>Nome<input value={name} onChange={e=>setName(e.target.value)} autoFocus maxLength={160} required placeholder="Nome do cliente"/></label><label>Telefone<input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" maxLength={32} placeholder="(11) 99999-9999"/></label>{formError&&<div className="form-error">{formError}</div>}<div className="dialog-actions"><button type="button" onClick={close} disabled={saving}>Cancelar</button><button className="primary" disabled={saving}>{saving?'Salvando…':'Cadastrar cliente'}</button></div></form></div>}</section>}
