import { useState, type FormEvent } from 'react';
import { CalendarDays, CircleDollarSign, LayoutDashboard, Radar, Users } from 'lucide-react';
import { useAuthTenant } from './auth/AuthTenantProvider';
import { ClientsPage } from './clients/ClientsPage';
import { AgendaPage } from './agenda/AgendaPage';
type Module='Dashboard'|'Agenda'|'Clientes'|'Caixa'|'Radar';
const modules:[Module,typeof LayoutDashboard][]=[['Dashboard',LayoutDashboard],['Agenda',CalendarDays],['Clientes',Users],['Caixa',CircleDollarSign],['Radar',Radar]];
export function App(){
 const auth=useAuthTenant();const [active,setActive]=useState<Module>('Dashboard');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [loginError,setLoginError]=useState<string|null>(null);const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setLoginError(null);const error=await auth.signIn(email.trim(),password);setLoginError(error);setBusy(false);}
 if(auth.status==='loading')return <div className="gate"><strong>Salúnea</strong><p>Carregando sua sessão…</p></div>;
 if(auth.status==='signed_out')return <div className="gate"><form className="login" onSubmit={submit}><small>GESTÃO INTELIGENTE</small><h1>Bem-vindo</h1><p>Acesse sua conta para continuar.</p><label>E-mail<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Senha<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button disabled={busy}>{busy?'Entrando…':'Entrar'}</button>{loginError&&<div className="error">Não foi possível entrar. Confira suas credenciais.</div>}</form></div>;
 if(auth.status==='error')return <div className="gate"><strong>Salúnea</strong><p>{auth.error}</p><button onClick={()=>auth.reload()}>Tentar novamente</button></div>;
 const dashboard=<section className="content"><p className="eyebrow">CONVERGÊNCIA SEGURA</p><h1>{auth.status==='needs_unit'?'Selecione a unidade para continuar.':'Sessão e tenant conectados ao backend real.'}</h1><p className="lead">O React agora resolve usuário, empresa e unidade pelos mesmos vínculos protegidos usados pelo C12. Nenhum dado operacional mock é carregado.</p><div className="grid"><article><span>Usuário</span><strong>{auth.appUser?.full_name||auth.appUser?.email}</strong><p>Perfil provisionado no SaaS.</p></article><article><span>Empresa</span><strong>{auth.company?.trade_name||auth.company?.legal_name}</strong><p>Vínculo obtido por company_users ativo.</p></article><article><span>Unidade</span><strong>{auth.unit?.name||'Pendente'}</strong><p>{auth.unit?.timezone||'Escolha uma unidade acessível.'}</p></article></div></section>;
 const page=active==='Agenda'?<AgendaPage/>:active==='Clientes'?<ClientsPage/>:dashboard;
 return <div className="shell"><aside className="sidebar"><div className="brand">Salúnea</div><nav>{modules.map(([name,Icon])=><button onClick={()=>setActive(name)} className={active===name?'active':''} key={name}><Icon size={18}/><span>{name}</span></button>)}</nav><small>Convergência React · backend real</small></aside><main><header><div><strong>{auth.company?.trade_name||auth.company?.legal_name||'Salúnea'}</strong><span>{auth.unit?.name||'Selecione a unidade'}</span></div><div className="tenant-controls">{auth.companies.length>1&&<select value={auth.company?.id||''} onChange={e=>void auth.selectCompany(e.target.value)}>{auth.companies.map(x=><option key={x.id} value={x.id}>{x.trade_name||x.legal_name}</option>)}</select>}{auth.units.length>1&&<select value={auth.unit?.id||''} onChange={e=>auth.selectUnit(e.target.value)}><option value="">Selecione a unidade</option>{auth.units.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}<button onClick={()=>void auth.signOut()}>Sair</button></div></header>{auth.status==='needs_unit'?dashboard:page}</main></div>}
