import { useEffect,useMemo,useState,type FormEvent } from 'react';
import { CalendarPlus } from 'lucide-react';
import { useAuthTenant } from '../auth/AuthTenantProvider';
import { createAppointment,getAgendaClient,listAgendaClients,listAgendaLabels,listBookableServices,listDayAppointments,listProfessionalsForService,type AgendaClient,type AgendaItem,type AgendaProfessional,type AgendaService } from './agendaService';
import { formatUnitTime,nextDateText,unitDateText,zonedDateTimeToIso } from '../lib/timezone';

export function AgendaPage({initialClientId=null}:{initialClientId?:string|null}){const {company,unit}=useAuthTenant();const zone=unit?.timezone||'America/Sao_Paulo';const [date,setDate]=useState(()=>unitDateText(zone));const [clients,setClients]=useState<AgendaClient[]>([]);const [clientSearch,setClientSearch]=useState('');const [services,setServices]=useState<AgendaService[]>([]);const [professionals,setProfessionals]=useState<AgendaProfessional[]>([]);const [items,setItems]=useState<AgendaItem[]>([]);const [labels,setLabels]=useState<{services:Record<string,string>;professionals:Record<string,string>}>({services:{},professionals:{}});const [status,setStatus]=useState<'loading'|'ready'|'error'>('loading');const [clientId,setClientId]=useState('');const [serviceId,setServiceId]=useState('');const [professionalId,setProfessionalId]=useState('');const [time,setTime]=useState('');const [notes,setNotes]=useState('');const [saving,setSaving]=useState(false);const [formError,setFormError]=useState<string|null>(null);
 useEffect(()=>{setDate(unitDateText(zone))},[unit?.id,zone]);
 async function load(){if(!company||!unit)return;setStatus('loading');try{const start=zonedDateTimeToIso(date,'00:00',zone),end=zonedDateTimeToIso(nextDateText(date),'00:00',zone);const [c,s,a]=await Promise.all([listAgendaClients(company.id,clientSearch),listBookableServices(company.id,unit.id),listDayAppointments(company.id,unit.id,start,end)]);setClients(c);setServices(s);setItems(a);setLabels(await listAgendaLabels(company.id,a));setStatus('ready')}catch{setStatus('error')}}
 useEffect(()=>{const timer=window.setTimeout(()=>{void load()},250);return()=>window.clearTimeout(timer)},[company?.id,unit?.id,date,zone,clientSearch]);
 useEffect(()=>{if(!company||!initialClientId)return;const current=clients.some(c=>c.id===initialClientId);if(current){setClientId(initialClientId);return}void getAgendaClient(company.id,initialClientId).then(client=>{if(client){setClients(prev=>prev.some(c=>c.id===client.id)?prev:[client,...prev]);setClientId(client.id)}}).catch(()=>undefined)},[company?.id,initialClientId,clients]);
 useEffect(()=>{setProfessionalId('');if(!company||!unit||!serviceId){setProfessionals([]);return}void listProfessionalsForService(company.id,unit.id,serviceId).then(setProfessionals).catch(()=>setProfessionals([]))},[company?.id,unit?.id,serviceId]);
 const clientNames=useMemo(()=>new Map(clients.map(c=>[c.id,c.full_name])),[clients]);
 async function submit(e:FormEvent){e.preventDefault();if(!company||!unit)return;if(!clientId||!serviceId||!professionalId||!time){setFormError('Preencha cliente, serviço, profissional e horário.');return}setSaving(true);setFormError(null);try{const startsAt=zonedDateTimeToIso(date,time,zone);await createAppointment({companyId:company.id,unitId:unit.id,clientId,serviceId,professionalId,startsAt,notes});setTime('');setNotes('');await load()}catch{setFormError('Não foi possível criar o agendamento. Verifique disponibilidade, horário e dados selecionados.')}finally{setSaving(false)}}
 return <section className="content agenda-page"><div className="page-head"><div><p className="eyebrow">AGENDA</p><h1>Transforme relacionamento em próxima visita.</h1><p className="lead">A agenda usa o fuso da unidade ({zone}), não o relógio do dispositivo. Serviços e profissionais continuam filtrados pelas regras reais do backend.</p></div><label className="date-control">Dia<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div><div className="agenda-layout"><form className="booking-card" onSubmit={submit}><h2><CalendarPlus size={20}/>Novo agendamento</h2><label>Buscar cliente<input type="search" value={clientSearch} onChange={e=>setClientSearch(e.target.value)} placeholder="Nome ou telefone" autoComplete="off"/></label><label>Cliente<select value={clientId} onChange={e=>setClientId(e.target.value)} required><option value="">{clientSearch?'Selecione um resultado':'Digite nome ou telefone'}</option>{clients.map(c=><option key={c.id} value={c.id}>{c.full_name}{c.phone?` · ${c.phone}`:''}</option>)}</select></label><small className="field-hint">Mostrando até 50 clientes por busca.</small><label>Serviço<select value={serviceId} onChange={e=>setServiceId(e.target.value)} required><option value="">Selecione</option>{services.map(s=><option key={s.id} value={s.id}>{s.name} · R$ {s.price.toFixed(2)} · {s.duration} min</option>)}</select></label><label>Profissional<select value={professionalId} onChange={e=>setProfessionalId(e.target.value)} disabled={!serviceId} required><option value="">Selecione</option>{professionals.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Horário da unidade<input type="time" value={time} onChange={e=>setTime(e.target.value)} required/></label><label>Observações<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3}/></label>{formError&&<div className="form-error">{formError}</div>}<button className="primary" disabled={saving}>{saving?'Agendando…':'Confirmar agendamento'}</button></form><div className="day-card"><h2>Agenda do dia</h2>{status==='loading'&&<div className="state-card">Carregando agenda real…</div>}{status==='error'&&<div className="state-card error">Não foi possível carregar a agenda.<button onClick={()=>void load()}>Tentar novamente</button></div>}{status==='ready'&&items.length===0&&<div className="state-card">Nenhum horário agendado neste dia.</div>}{status==='ready'&&items.map(a=><article className="appointment-row" key={a.id}><time>{formatUnitTime(a.starts_at,zone)}</time><div><strong>{a.client_id?clientNames.get(a.client_id)||'Cliente':'Sem cliente'}</strong><span>{a.service_id?labels.services[a.service_id]||'Serviço':'Serviço'} · {a.professional_id?labels.professionals[a.professional_id]||'Profissional':'Profissional'} · {a.status}</span></div></article>)}</div></div></section>}
