import { useEffect,useMemo,useState } from 'react';
import { CalendarPlus,RefreshCw,UserRound,MessageCircle } from 'lucide-react';
import { useAuthTenant } from '../auth/AuthTenantProvider';
import { clientIdFromSignal,listRadarClients,listRadarSignals,runRadarCycle,type RadarClient,type RadarSignal } from './radarService';
const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n||0);
function level(s:RadarSignal){const st=String(s.evidence?.status||'');if(st==='late')return{label:'Atrasado',tone:'red'};if(st==='at_risk')return{label:'Em risco',tone:'orange'};if(st==='attention')return{label:'Momento ideal',tone:'yellow'};if(s.urgency>=4)return{label:'Atenção alta',tone:'orange'};return{label:'Monitorado',tone:'blue'}}
export function RadarPage(){const {company,unit}=useAuthTenant();const [signals,setSignals]=useState<RadarSignal[]>([]);const [clients,setClients]=useState<RadarClient[]>([]);const [status,setStatus]=useState<'loading'|'ready'|'error'>('loading');const [refreshing,setRefreshing]=useState(false);const [feedback,setFeedback]=useState<string|null>(null);
 async function load(run=false){if(!company||!unit)return;run?setRefreshing(true):setStatus('loading');setFeedback(null);try{if(run)await runRadarCycle(company.id,unit.id);const rows=await listRadarSignals(company.id,unit.id);setSignals(rows);const ids=rows.map(clientIdFromSignal).filter((x):x is string=>Boolean(x));setClients(await listRadarClients(company.id,ids));setStatus('ready');if(run)setFeedback('Radar atualizado com os dados disponíveis agora.')}catch{if(!run)setStatus('error');setFeedback('Não foi possível atualizar o Radar. Os sinais não foram inventados nem recalculados no navegador.')}finally{setRefreshing(false)}}
 useEffect(()=>{void load(true)},[company?.id,unit?.id]);const byClient=useMemo(()=>new Map(clients.map(x=>[x.id,x])),[clients]);const clientSignals=signals.filter(x=>clientIdFromSignal(x));const potential=clientSignals.reduce((sum,x)=>sum+Math.max(0,Number(x.impact_amount||0)),0);
 return <section className="content radar-page"><div className="page-head"><div><p className="eyebrow">RADAR DE CLIENTES</p><h1>Quem precisa da sua atenção hoje.</h1><p className="lead">O Radar transforma histórico concluído em prioridade de relacionamento. A inteligência permanece no backend; esta tela apenas apresenta sinais determinísticos e ações.</p></div><button className="primary" disabled={refreshing} onClick={()=>void load(true)}><RefreshCw size={16}/>{refreshing?'Atualizando…':'Atualizar Radar'}</button></div><div className="grid"><article><span>Clientes em atenção</span><strong>{clientSignals.length}</strong><p>Sinais abertos ou reconhecidos nesta unidade.</p></article><article><span>Receita potencial de retorno</span><strong>{money(potential)}</strong><p>Estimativa baseada no histórico; não é receita garantida.</p></article><article><span>Sinais operacionais</span><strong>{signals.length-clientSignals.length}</strong><p>Outros sinais determinísticos do Radar.</p></article></div>{feedback&&<div className="state-card">{feedback}</div>}{status==='loading'&&<div className="state-card">Atualizando ciclos e consultando sinais…</div>}{status==='error'&&<div className="state-card error">Não foi possível carregar o Radar.<button onClick={()=>void load(true)}>Tentar novamente</button></div>}{status==='ready'&&<div className="radar-list">{clientSignals.length===0?<div className="state-card">Nenhum cliente exige ação de retorno neste momento.</div>:clientSignals.map(s=>{const id=clientIdFromSignal(s),c=id?byClient.get(id):undefined,l=level(s),phone=(c?.phone||'').replace(/\D/g,'');return <article className={`operation-card radar-card ${l.tone}`} key={s.id}><div className="radar-card-head"><div><span className="done-badge">{l.label}</span><h2>{c?.full_name||'Cliente'}</h2></div><strong>{money(s.impact_amount)}</strong></div><p>{s.title_pt_br}</p><small>{s.diagnosis_pt_br}</small><div className="cash-summary"><div><span>Prioridade</span><strong>{s.urgency>=4?'Alta':s.urgency>=2?'Média':'Baixa'}</strong></div><div><span>Confiança</span><strong>{s.confidence==='high'?'Alta':s.confidence==='medium'?'Média':'Baixa'}</strong></div><div><span>Potencial</span><strong>{money(s.impact_amount)}</strong></div></div><div className="dialog-actions"><button title="Cliente"><UserRound size={15}/>Ver cliente</button><button disabled={!phone||c?.whatsapp_opt_in!==true} title={c?.whatsapp_opt_in===true?'Abrir conversa autorizada':'WhatsApp requer consentimento'} onClick={()=>{if(phone&&c?.whatsapp_opt_in===true)window.open(`https://wa.me/${phone}`,'_blank','noopener,noreferrer')}}><MessageCircle size={15}/>WhatsApp</button><button title="Abra Agenda para agendar o retorno"><CalendarPlus size={15}/>Agendar</button></div></article>})}</div>}</section>}
